// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Light/AmbientLightComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UAmbientLightComponent ----
UClass UAmbientLightComponent::StaticClassInstance(
    "UAmbientLightComponent",
    &ULightComponent::StaticClassInstance,
    sizeof(UAmbientLightComponent),
    CF_None
);
FClassRegistrar UAmbientLightComponent::s_Registrar(&UAmbientLightComponent::StaticClassInstance);

