// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Light/DirectionalLightComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UDirectionalLightComponent ----
UClass UDirectionalLightComponent::StaticClassInstance(
    "UDirectionalLightComponent",
    &ULightComponent::StaticClassInstance,
    sizeof(UDirectionalLightComponent),
    CF_None
);
FClassRegistrar UDirectionalLightComponent::s_Registrar(&UDirectionalLightComponent::StaticClassInstance);

