// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Light/LightComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- ULightComponent ----
UClass ULightComponent::StaticClassInstance(
    "ULightComponent",
    &ULightComponentBase::StaticClassInstance,
    sizeof(ULightComponent),
    CF_None
);
FClassRegistrar ULightComponent::s_Registrar(&ULightComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& ULightComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata ULightComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "Shadow Resolution Scale", offsetof(ULightComponent, ShadowResolutionScale), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.1f, 4.0f, 0.1f, &ULightComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "Shadow Resolution Scale", offsetof(ULightComponent, ShadowResolutionScale), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.1f, 4.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata ULightComponent_EditorMeta_26{ "Default", "" };
            return FPropertyMetadata{ "Shadow Bias", offsetof(ULightComponent, ShadowBias), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, -0.2f, 0.2f, 0.0001f, &ULightComponent_EditorMeta_26 };
        }(),
        #else
        FPropertyMetadata{ "Shadow Bias", offsetof(ULightComponent, ShadowBias), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, -0.2f, 0.2f, 0.0001f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata ULightComponent_EditorMeta_34{ "Default", "" };
            return FPropertyMetadata{ "Shadow Slope Bias", offsetof(ULightComponent, ShadowSlopeBias), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, -0.2f, 0.2f, 0.0001f, &ULightComponent_EditorMeta_34 };
        }(),
        #else
        FPropertyMetadata{ "Shadow Slope Bias", offsetof(ULightComponent, ShadowSlopeBias), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, -0.2f, 0.2f, 0.0001f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata ULightComponent_EditorMeta_42{ "Default", "" };
            return FPropertyMetadata{ "Shadow Normal Bias", offsetof(ULightComponent, ShadowNormalBias), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, -0.2f, 0.2f, 0.0001f, &ULightComponent_EditorMeta_42 };
        }(),
        #else
        FPropertyMetadata{ "Shadow Normal Bias", offsetof(ULightComponent, ShadowNormalBias), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, -0.2f, 0.2f, 0.0001f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata ULightComponent_EditorMeta_50{ "Default", "" };
            return FPropertyMetadata{ "Shadow Sharpen", offsetof(ULightComponent, ShadowSharpen), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 1.0f, 0.05f, &ULightComponent_EditorMeta_50 };
        }(),
        #else
        FPropertyMetadata{ "Shadow Sharpen", offsetof(ULightComponent, ShadowSharpen), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 1.0f, 0.05f },
        #endif
    };
    return Props;
}

static bool ULightComponent_MetaRegistered = []() {
    ULightComponent::StaticClassInstance.SetMetadataGetter(
        &ULightComponent::GetReflectedMetadata);
    return true;
}();

