// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Light/LightComponentBase.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- ULightComponentBase ----
UClass ULightComponentBase::StaticClassInstance(
    "ULightComponentBase",
    &USceneComponent::StaticClassInstance,
    sizeof(ULightComponentBase),
    CF_None
);
FClassRegistrar ULightComponentBase::s_Registrar(&ULightComponentBase::StaticClassInstance);

const std::vector<FPropertyMetadata>& ULightComponentBase::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata ULightComponentBase_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "Intensity", offsetof(ULightComponentBase, Intensity), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 50.f, 0.05f, &ULightComponentBase_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "Intensity", offsetof(ULightComponentBase, Intensity), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 50.f, 0.05f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata ULightComponentBase_EditorMeta_26{ "Default", "" };
            return FPropertyMetadata{ "Color", offsetof(ULightComponentBase, LightColor), GetBuiltinPropertyType(EPropertyType::Color4), EPF_None, 0.0f, 0.0f, 0.1f, &ULightComponentBase_EditorMeta_26 };
        }(),
        #else
        FPropertyMetadata{ "Color", offsetof(ULightComponentBase, LightColor), GetBuiltinPropertyType(EPropertyType::Color4), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata ULightComponentBase_EditorMeta_34{ "Default", "" };
            return FPropertyMetadata{ "Visible", offsetof(ULightComponentBase, bVisible), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &ULightComponentBase_EditorMeta_34 };
        }(),
        #else
        FPropertyMetadata{ "Visible", offsetof(ULightComponentBase, bVisible), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata ULightComponentBase_EditorMeta_42{ "Default", "" };
            return FPropertyMetadata{ "Cast Shadows", offsetof(ULightComponentBase, bCastShadows), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &ULightComponentBase_EditorMeta_42 };
        }(),
        #else
        FPropertyMetadata{ "Cast Shadows", offsetof(ULightComponentBase, bCastShadows), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool ULightComponentBase_MetaRegistered = []() {
    ULightComponentBase::StaticClassInstance.SetMetadataGetter(
        &ULightComponentBase::GetReflectedMetadata);
    return true;
}();

