// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Light/PointLightComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UPointLightComponent ----
UClass UPointLightComponent::StaticClassInstance(
    "UPointLightComponent",
    &ULightComponent::StaticClassInstance,
    sizeof(UPointLightComponent),
    CF_None
);
FClassRegistrar UPointLightComponent::s_Registrar(&UPointLightComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UPointLightComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UPointLightComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "AttenuationRadius", offsetof(UPointLightComponent, AttenuationRadius), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.05f, 1000.f, 0.01f, &UPointLightComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "AttenuationRadius", offsetof(UPointLightComponent, AttenuationRadius), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.05f, 1000.f, 0.01f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UPointLightComponent_EditorMeta_26{ "Default", "" };
            return FPropertyMetadata{ "LightFalloffExponent", offsetof(UPointLightComponent, LightFalloffExponent), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.05f, 10.f, 0.01f, &UPointLightComponent_EditorMeta_26 };
        }(),
        #else
        FPropertyMetadata{ "LightFalloffExponent", offsetof(UPointLightComponent, LightFalloffExponent), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.05f, 10.f, 0.01f },
        #endif
    };
    return Props;
}

static bool UPointLightComponent_MetaRegistered = []() {
    UPointLightComponent::StaticClassInstance.SetMetadataGetter(
        &UPointLightComponent::GetReflectedMetadata);
    return true;
}();

