// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Light/SpotLightComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- USpotLightComponent ----
UClass USpotLightComponent::StaticClassInstance(
    "USpotLightComponent",
    &UPointLightComponent::StaticClassInstance,
    sizeof(USpotLightComponent),
    CF_None
);
FClassRegistrar USpotLightComponent::s_Registrar(&USpotLightComponent::StaticClassInstance);

