// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Camera/CameraVignetteModifier.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UVignetteModifier ----
UClass UVignetteModifier::StaticClassInstance(
    "UVignetteModifier",
    &UCameraModifier::StaticClassInstance,
    sizeof(UVignetteModifier),
    CF_None
);
FClassRegistrar UVignetteModifier::s_Registrar(&UVignetteModifier::StaticClassInstance);

