// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Camera/CameraModifier.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UCameraModifier ----
UClass UCameraModifier::StaticClassInstance(
    "UCameraModifier",
    &UObject::StaticClassInstance,
    sizeof(UCameraModifier),
    CF_None
);
FClassRegistrar UCameraModifier::s_Registrar(&UCameraModifier::StaticClassInstance);

