// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Camera/CameraShakeModifier.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UCameraShakeModifier ----
UClass UCameraShakeModifier::StaticClassInstance(
    "UCameraShakeModifier",
    &UCameraModifier::StaticClassInstance,
    sizeof(UCameraShakeModifier),
    CF_None
);
FClassRegistrar UCameraShakeModifier::s_Registrar(&UCameraShakeModifier::StaticClassInstance);

