// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Camera/CameraFadeModifier.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UCameraFadeModifier ----
UClass UCameraFadeModifier::StaticClassInstance(
    "UCameraFadeModifier",
    &UCameraModifier::StaticClassInstance,
    sizeof(UCameraFadeModifier),
    CF_None
);
FClassRegistrar UCameraFadeModifier::s_Registrar(&UCameraFadeModifier::StaticClassInstance);

