// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Camera/PlayerCameraManager.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- APlayerCameraManager ----
UClass APlayerCameraManager::StaticClassInstance(
    "APlayerCameraManager",
    &AActor::StaticClassInstance,
    sizeof(APlayerCameraManager),
    CF_None
);
FClassRegistrar APlayerCameraManager::s_Registrar(&APlayerCameraManager::StaticClassInstance);

