// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Asset/Import/FBX/Types/FBXSceneAsset.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UFBXSceneAsset ----
UClass UFBXSceneAsset::StaticClassInstance(
    "UFBXSceneAsset",
    &UObject::StaticClassInstance,
    sizeof(UFBXSceneAsset),
    CF_None
);
FClassRegistrar UFBXSceneAsset::s_Registrar(&UFBXSceneAsset::StaticClassInstance);

