// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Asset/Texture/Texture2D.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UTexture2D ----
UClass UTexture2D::StaticClassInstance(
    "UTexture2D",
    &UObject::StaticClassInstance,
    sizeof(UTexture2D),
    CF_None
);
FClassRegistrar UTexture2D::s_Registrar(&UTexture2D::StaticClassInstance);

