// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Asset/Material/Material.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UMaterial ----
UClass UMaterial::StaticClassInstance(
    "UMaterial",
    &UObject::StaticClassInstance,
    sizeof(UMaterial),
    CF_None
);
FClassRegistrar UMaterial::s_Registrar(&UMaterial::StaticClassInstance);

