// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Movement/InterpToMovementComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UInterpToMovementComponent ----
UClass UInterpToMovementComponent::StaticClassInstance(
    "UInterpToMovementComponent",
    &UMovementComponent::StaticClassInstance,
    sizeof(UInterpToMovementComponent),
    CF_None
);
FClassRegistrar UInterpToMovementComponent::s_Registrar(&UInterpToMovementComponent::StaticClassInstance);

const std::vector<FPropertyDescriptor>& UInterpToMovementComponent::GetReflectedProperties() {
    static std::vector<FPropertyDescriptor> Props = {
        FPropertyDescriptor{ "Control Points", EPropertyType::Array, reinterpret_cast<void*>(offsetof(UInterpToMovementComponent, ControlPoints)), 0.0f, 0.0f, 0.1f, nullptr, 0, "Default", "", 0, nullptr, EPropertyType::Vec3, &TArrayPropertyOps<TArray<FVector>>::GetSize, &TArrayPropertyOps<TArray<FVector>>::Resize, &TArrayPropertyOps<TArray<FVector>>::GetElement, &TArrayPropertyOps<TArray<FVector>>::GetConstElement },
        FPropertyDescriptor{ "Auto Activate", EPropertyType::Bool, reinterpret_cast<void*>(offsetof(UInterpToMovementComponent, bAutoActivate)), 0.0f, 0.0f, 0.1f, nullptr, 0, "Default", "", 0, nullptr, EPropertyType::Int, nullptr, nullptr, nullptr, nullptr },
        FPropertyDescriptor{ "Orient To Movement", EPropertyType::Bool, reinterpret_cast<void*>(offsetof(UInterpToMovementComponent, bFaceTargetDir)), 0.0f, 0.0f, 0.1f, nullptr, 0, "Default", "", 0, nullptr, EPropertyType::Int, nullptr, nullptr, nullptr, nullptr },
    };
    return Props;
}

static bool UInterpToMovementComponent_PropsRegistered = []() {
    UInterpToMovementComponent::StaticClassInstance.SetPropertiesGetter(
        &UInterpToMovementComponent::GetReflectedProperties);
    return true;
}();

