// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Movement/InterpToMovementComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UInterpToMovementComponent ----
UClass UInterpToMovementComponent::StaticClassInstance(
    "UInterpToMovementComponent",
    &UMovementComponent::StaticClassInstance,
    sizeof(UInterpToMovementComponent),
    CF_None
);
FClassRegistrar UInterpToMovementComponent::s_Registrar(&UInterpToMovementComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UInterpToMovementComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static const FPropertyTypeDesc UInterpToMovementComponent_PropType_0{ EPropertyType::Array, nullptr, nullptr, 0, nullptr, &TArrayPropertyOps<TArray<FVector>>::GetSize, &TArrayPropertyOps<TArray<FVector>>::Resize, &TArrayPropertyOps<TArray<FVector>>::GetElement, &TArrayPropertyOps<TArray<FVector>>::GetConstElement, GetBuiltinPropertyType(EPropertyType::Vec3), nullptr, nullptr };
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UInterpToMovementComponent_EditorMeta_19{ "Default", "" };
            return FPropertyMetadata{ "Control Points", offsetof(UInterpToMovementComponent, ControlPoints), &UInterpToMovementComponent_PropType_0, EPF_None, 0.0f, 0.0f, 0.1f, &UInterpToMovementComponent_EditorMeta_19 };
        }(),
        #else
        FPropertyMetadata{ "Control Points", offsetof(UInterpToMovementComponent, ControlPoints), &UInterpToMovementComponent_PropType_0, EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UInterpToMovementComponent_EditorMeta_27{ "Default", "" };
            return FPropertyMetadata{ "Auto Activate", offsetof(UInterpToMovementComponent, bAutoActivate), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UInterpToMovementComponent_EditorMeta_27 };
        }(),
        #else
        FPropertyMetadata{ "Auto Activate", offsetof(UInterpToMovementComponent, bAutoActivate), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UInterpToMovementComponent_EditorMeta_35{ "Default", "" };
            return FPropertyMetadata{ "Orient To Movement", offsetof(UInterpToMovementComponent, bFaceTargetDir), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UInterpToMovementComponent_EditorMeta_35 };
        }(),
        #else
        FPropertyMetadata{ "Orient To Movement", offsetof(UInterpToMovementComponent, bFaceTargetDir), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool UInterpToMovementComponent_MetaRegistered = []() {
    UInterpToMovementComponent::StaticClassInstance.SetMetadataGetter(
        &UInterpToMovementComponent::GetReflectedMetadata);
    return true;
}();

