// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Movement/MovementComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UMovementComponent ----
UClass UMovementComponent::StaticClassInstance(
    "UMovementComponent",
    &UActorComponent::StaticClassInstance,
    sizeof(UMovementComponent),
    CF_None
);
FClassRegistrar UMovementComponent::s_Registrar(&UMovementComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UMovementComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static const FPropertyTypeDesc UMovementComponent_PropType_1{ EPropertyType::ObjectRef, nullptr, nullptr, 0, FindRegisteredClassByName("USceneComponent"), nullptr, nullptr, nullptr, nullptr, nullptr, nullptr };
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UMovementComponent_EditorMeta_19{ "Default", "" };
            return FPropertyMetadata{ "Auto Register Updated", offsetof(UMovementComponent, bAutoRegisterUpdatedComponent), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UMovementComponent_EditorMeta_19 };
        }(),
        #else
        FPropertyMetadata{ "Auto Register Updated", offsetof(UMovementComponent, bAutoRegisterUpdatedComponent), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UMovementComponent_EditorMeta_27{ "Default", "" };
            return FPropertyMetadata{ "Updated Component", offsetof(UMovementComponent, UpdatedComponentPath), &UMovementComponent_PropType_1, EPF_None, 0.0f, 0.0f, 0.1f, &UMovementComponent_EditorMeta_27 };
        }(),
        #else
        FPropertyMetadata{ "Updated Component", offsetof(UMovementComponent, UpdatedComponentPath), &UMovementComponent_PropType_1, EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UMovementComponent_EditorMeta_35{ "Default", "" };
            return FPropertyMetadata{ "Receive Controller Input", offsetof(UMovementComponent, bReceiveControllerInput), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UMovementComponent_EditorMeta_35 };
        }(),
        #else
        FPropertyMetadata{ "Receive Controller Input", offsetof(UMovementComponent, bReceiveControllerInput), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UMovementComponent_EditorMeta_43{ "Default", "" };
            return FPropertyMetadata{ "Controller Input Priority", offsetof(UMovementComponent, ControllerInputPriority), GetBuiltinPropertyType(EPropertyType::Int), EPF_None, -100.0f, 100.0f, 1.0f, &UMovementComponent_EditorMeta_43 };
        }(),
        #else
        FPropertyMetadata{ "Controller Input Priority", offsetof(UMovementComponent, ControllerInputPriority), GetBuiltinPropertyType(EPropertyType::Int), EPF_None, -100.0f, 100.0f, 1.0f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UMovementComponent_EditorMeta_51{ "Default", "" };
            return FPropertyMetadata{ "Last Controller Direction", offsetof(UMovementComponent, LastControllerWorldDirection), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f, &UMovementComponent_EditorMeta_51 };
        }(),
        #else
        FPropertyMetadata{ "Last Controller Direction", offsetof(UMovementComponent, LastControllerWorldDirection), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UMovementComponent_EditorMeta_59{ "Default", "" };
            return FPropertyMetadata{ "Last Controller Delta", offsetof(UMovementComponent, LastControllerWorldDelta), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f, &UMovementComponent_EditorMeta_59 };
        }(),
        #else
        FPropertyMetadata{ "Last Controller Delta", offsetof(UMovementComponent, LastControllerWorldDelta), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool UMovementComponent_MetaRegistered = []() {
    UMovementComponent::StaticClassInstance.SetMetadataGetter(
        &UMovementComponent::GetReflectedMetadata);
    return true;
}();

