// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Movement/PawnMovementComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UPawnMovementComponent ----
UClass UPawnMovementComponent::StaticClassInstance(
    "UPawnMovementComponent",
    &UMovementComponent::StaticClassInstance,
    sizeof(UPawnMovementComponent),
    CF_None
);
FClassRegistrar UPawnMovementComponent::s_Registrar(&UPawnMovementComponent::StaticClassInstance);

