// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Movement/PendulumMovementComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UPendulumMovementComponent ----
UClass UPendulumMovementComponent::StaticClassInstance(
    "UPendulumMovementComponent",
    &UMovementComponent::StaticClassInstance,
    sizeof(UPendulumMovementComponent),
    CF_None
);
FClassRegistrar UPendulumMovementComponent::s_Registrar(&UPendulumMovementComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UPendulumMovementComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UPendulumMovementComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "Swing Axis", offsetof(UPendulumMovementComponent, Axis), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f, &UPendulumMovementComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "Swing Axis", offsetof(UPendulumMovementComponent, Axis), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool UPendulumMovementComponent_MetaRegistered = []() {
    UPendulumMovementComponent::StaticClassInstance.SetMetadataGetter(
        &UPendulumMovementComponent::GetReflectedMetadata);
    return true;
}();

