// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Movement/ProjectileMovementComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UProjectileMovementComponent ----
UClass UProjectileMovementComponent::StaticClassInstance(
    "UProjectileMovementComponent",
    &UMovementComponent::StaticClassInstance,
    sizeof(UProjectileMovementComponent),
    CF_None
);
FClassRegistrar UProjectileMovementComponent::s_Registrar(&UProjectileMovementComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UProjectileMovementComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UProjectileMovementComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "Velocity", offsetof(UProjectileMovementComponent, Velocity), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 1.0f, &UProjectileMovementComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "Velocity", offsetof(UProjectileMovementComponent, Velocity), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 1.0f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UProjectileMovementComponent_EditorMeta_26{ "Default", "" };
            return FPropertyMetadata{ "Initial Speed", offsetof(UProjectileMovementComponent, InitialSpeed), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 0.0f, 10.0f, &UProjectileMovementComponent_EditorMeta_26 };
        }(),
        #else
        FPropertyMetadata{ "Initial Speed", offsetof(UProjectileMovementComponent, InitialSpeed), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 0.0f, 10.0f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UProjectileMovementComponent_EditorMeta_34{ "Default", "" };
            return FPropertyMetadata{ "Max Speed", offsetof(UProjectileMovementComponent, MaxSpeed), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 0.0f, 10.0f, &UProjectileMovementComponent_EditorMeta_34 };
        }(),
        #else
        FPropertyMetadata{ "Max Speed", offsetof(UProjectileMovementComponent, MaxSpeed), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 0.0f, 10.0f },
        #endif
    };
    return Props;
}

static bool UProjectileMovementComponent_MetaRegistered = []() {
    UProjectileMovementComponent::StaticClassInstance.SetMetadataGetter(
        &UProjectileMovementComponent::GetReflectedMetadata);
    return true;
}();

