// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Movement/RotatingMovementComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- URotatingMovementComponent ----
UClass URotatingMovementComponent::StaticClassInstance(
    "URotatingMovementComponent",
    &UMovementComponent::StaticClassInstance,
    sizeof(URotatingMovementComponent),
    CF_None
);
FClassRegistrar URotatingMovementComponent::s_Registrar(&URotatingMovementComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& URotatingMovementComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata URotatingMovementComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "Rotation Rate", offsetof(URotatingMovementComponent, RotationRate), GetBuiltinPropertyType(EPropertyType::Rotator), EPF_None, 0.0f, 0.0f, 0.1f, &URotatingMovementComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "Rotation Rate", offsetof(URotatingMovementComponent, RotationRate), GetBuiltinPropertyType(EPropertyType::Rotator), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool URotatingMovementComponent_MetaRegistered = []() {
    URotatingMovementComponent::StaticClassInstance.SetMetadataGetter(
        &URotatingMovementComponent::GetReflectedMetadata);
    return true;
}();

