// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Asset/Mesh/SkeletalMesh/SkeletalMesh.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- USkeletalMesh ----
UClass USkeletalMesh::StaticClassInstance(
    "USkeletalMesh",
    &UObject::StaticClassInstance,
    sizeof(USkeletalMesh),
    CF_None
);
FClassRegistrar USkeletalMesh::s_Registrar(&USkeletalMesh::StaticClassInstance);

