// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Editor/EditorEngine.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UEditorEngine ----
UClass UEditorEngine::StaticClassInstance(
    "UEditorEngine",
    &UEngine::StaticClassInstance,
    sizeof(UEditorEngine),
    CF_None
);
FClassRegistrar UEditorEngine::s_Registrar(&UEditorEngine::StaticClassInstance);

