// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Asset/Animation/Core/AnimSequence.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UAnimationAsset ----
UClass UAnimationAsset::StaticClassInstance(
    "UAnimationAsset",
    &UObject::StaticClassInstance,
    sizeof(UAnimationAsset),
    CF_None
);
FClassRegistrar UAnimationAsset::s_Registrar(&UAnimationAsset::StaticClassInstance);

// ---- UAnimDataModel ----
UClass UAnimDataModel::StaticClassInstance(
    "UAnimDataModel",
    &UObject::StaticClassInstance,
    sizeof(UAnimDataModel),
    CF_None
);
FClassRegistrar UAnimDataModel::s_Registrar(&UAnimDataModel::StaticClassInstance);

// ---- UAnimSequenceBase ----
UClass UAnimSequenceBase::StaticClassInstance(
    "UAnimSequenceBase",
    &UAnimationAsset::StaticClassInstance,
    sizeof(UAnimSequenceBase),
    CF_None
);
FClassRegistrar UAnimSequenceBase::s_Registrar(&UAnimSequenceBase::StaticClassInstance);

// ---- UAnimSequence ----
UClass UAnimSequence::StaticClassInstance(
    "UAnimSequence",
    &UAnimSequenceBase::StaticClassInstance,
    sizeof(UAnimSequence),
    CF_None
);
FClassRegistrar UAnimSequence::s_Registrar(&UAnimSequence::StaticClassInstance);

