// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Asset/Animation/Core/AnimSingleNodeInstance.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UAnimSingleNodeInstance ----
UClass UAnimSingleNodeInstance::StaticClassInstance(
    "UAnimSingleNodeInstance",
    &UAnimInstance::StaticClassInstance,
    sizeof(UAnimSingleNodeInstance),
    CF_None
);
FClassRegistrar UAnimSingleNodeInstance::s_Registrar(&UAnimSingleNodeInstance::StaticClassInstance);

