// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Asset/Animation/Core/AnimInstance.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UAnimInstance ----
UClass UAnimInstance::StaticClassInstance(
    "UAnimInstance",
    &UObject::StaticClassInstance,
    sizeof(UAnimInstance),
    CF_None
);
FClassRegistrar UAnimInstance::s_Registrar(&UAnimInstance::StaticClassInstance);

