// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Asset/Animation/Core/Skeleton.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- USkeleton ----
UClass USkeleton::StaticClassInstance(
    "USkeleton",
    &UObject::StaticClassInstance,
    sizeof(USkeleton),
    CF_None
);
FClassRegistrar USkeleton::s_Registrar(&USkeleton::StaticClassInstance);

