// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Asset/Mesh/StaticMesh/StaticMesh.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UStaticMesh ----
UClass UStaticMesh::StaticClassInstance(
    "UStaticMesh",
    &UObject::StaticClassInstance,
    sizeof(UStaticMesh),
    CF_None
);
FClassRegistrar UStaticMesh::s_Registrar(&UStaticMesh::StaticClassInstance);

