// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "ObjViewer/ObjViewerEngine.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UObjViewerEngine ----
UClass UObjViewerEngine::StaticClassInstance(
    "UObjViewerEngine",
    &UEngine::StaticClassInstance,
    sizeof(UObjViewerEngine),
    CF_None
);
FClassRegistrar UObjViewerEngine::s_Registrar(&UObjViewerEngine::StaticClassInstance);

