// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/GameFramework/AActor.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- AActor ----
UClass AActor::StaticClassInstance(
    "AActor",
    &UObject::StaticClassInstance,
    sizeof(AActor),
    CF_None
);
FClassRegistrar AActor::s_Registrar(&AActor::StaticClassInstance);

