// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/GameFramework/CameraActor.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- ACameraActor ----
UClass ACameraActor::StaticClassInstance(
    "ACameraActor",
    &AActor::StaticClassInstance,
    sizeof(ACameraActor),
    CF_None
);
FClassRegistrar ACameraActor::s_Registrar(&ACameraActor::StaticClassInstance);

