// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/GameFramework/DecalActor.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- ADecalActor ----
UClass ADecalActor::StaticClassInstance(
    "ADecalActor",
    &AActor::StaticClassInstance,
    sizeof(ADecalActor),
    CF_None
);
FClassRegistrar ADecalActor::s_Registrar(&ADecalActor::StaticClassInstance);

