// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/GameFramework/HeightFogActor.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- AHeightFogActor ----
UClass AHeightFogActor::StaticClassInstance(
    "AHeightFogActor",
    &AActor::StaticClassInstance,
    sizeof(AHeightFogActor),
    CF_None
);
FClassRegistrar AHeightFogActor::s_Registrar(&AHeightFogActor::StaticClassInstance);

