// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/GameFramework/Level.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- ULevel ----
UClass ULevel::StaticClassInstance(
    "ULevel",
    &UObject::StaticClassInstance,
    sizeof(ULevel),
    CF_None
);
FClassRegistrar ULevel::s_Registrar(&ULevel::StaticClassInstance);

