// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/GameFramework/Pawn.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- APawn ----
UClass APawn::StaticClassInstance(
    "APawn",
    &AActor::StaticClassInstance,
    sizeof(APawn),
    CF_None
);
FClassRegistrar APawn::s_Registrar(&APawn::StaticClassInstance);

