// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/GameFramework/PlayerController.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- APlayerController ----
UClass APlayerController::StaticClassInstance(
    "APlayerController",
    &AActor::StaticClassInstance,
    sizeof(APlayerController),
    CF_None
);
FClassRegistrar APlayerController::s_Registrar(&APlayerController::StaticClassInstance);

