// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/GameFramework/StaticMeshActor.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- AStaticMeshActor ----
UClass AStaticMeshActor::StaticClassInstance(
    "AStaticMeshActor",
    &AActor::StaticClassInstance,
    sizeof(AStaticMeshActor),
    CF_None
);
FClassRegistrar AStaticMeshActor::s_Registrar(&AStaticMeshActor::StaticClassInstance);

