// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/GameFramework/World.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UWorld ----
UClass UWorld::StaticClassInstance(
    "UWorld",
    &UObject::StaticClassInstance,
    sizeof(UWorld),
    CF_None
);
FClassRegistrar UWorld::s_Registrar(&UWorld::StaticClassInstance);

