// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#pragma once
#include "Object/ReflectionMacros.h"
#include <vector>

#undef  CURRENT_FILE_ID
#define CURRENT_FILE_ID World_h_LINE_

// ---- UWorld ----
#define World_h_LINE_28 \
    using Super = UObject; \
    static UClass StaticClassInstance; \
    static FClassRegistrar s_Registrar; \
    static UClass* StaticClass() { return &StaticClassInstance; } \
    virtual UClass* GetClass() const override { return StaticClass(); }

