// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Runtime/Engine.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UEngine ----
UClass UEngine::StaticClassInstance(
    "UEngine",
    &UObject::StaticClassInstance,
    sizeof(UEngine),
    CF_None
);
FClassRegistrar UEngine::s_Registrar(&UEngine::StaticClassInstance);

