// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Script/LuaScriptComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- ULuaScriptComponent ----
UClass ULuaScriptComponent::StaticClassInstance(
    "ULuaScriptComponent",
    &UActorComponent::StaticClassInstance,
    sizeof(ULuaScriptComponent),
    CF_None
);
FClassRegistrar ULuaScriptComponent::s_Registrar(&ULuaScriptComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& ULuaScriptComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata ULuaScriptComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "ScriptPath", offsetof(ULuaScriptComponent, ScriptPath), GetBuiltinPropertyType(EPropertyType::String), EPF_None, 0.0f, 0.0f, 0.1f, &ULuaScriptComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "ScriptPath", offsetof(ULuaScriptComponent, ScriptPath), GetBuiltinPropertyType(EPropertyType::String), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool ULuaScriptComponent_MetaRegistered = []() {
    ULuaScriptComponent::StaticClassInstance.SetMetadataGetter(
        &ULuaScriptComponent::GetReflectedMetadata);
    return true;
}();

