// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#pragma once
#include "Object/ReflectionMacros.h"
#include <vector>

#undef  CURRENT_FILE_ID
#define CURRENT_FILE_ID ActorComponent_h_LINE_

// ---- UActorComponent ----
#define ActorComponent_h_LINE_19 \
    using Super = UObject; \
    static UClass StaticClassInstance; \
    static FClassRegistrar s_Registrar; \
    static UClass* StaticClass() { return &StaticClassInstance; } \
    virtual UClass* GetClass() const override { return StaticClass(); } \
    static const std::vector<FPropertyMetadata>& GetReflectedMetadata();

