// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/ActorComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UActorComponent ----
UClass UActorComponent::StaticClassInstance(
    "UActorComponent",
    &UObject::StaticClassInstance,
    sizeof(UActorComponent),
    CF_None
);
FClassRegistrar UActorComponent::s_Registrar(&UActorComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UActorComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UActorComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "bTickEnable", offsetof(UActorComponent, bTickEnable), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UActorComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "bTickEnable", offsetof(UActorComponent, bTickEnable), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UActorComponent_EditorMeta_26{ "Default", "" };
            return FPropertyMetadata{ "bEditorOnly", offsetof(UActorComponent, bEditorOnly), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UActorComponent_EditorMeta_26 };
        }(),
        #else
        FPropertyMetadata{ "bEditorOnly", offsetof(UActorComponent, bEditorOnly), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool UActorComponent_MetaRegistered = []() {
    UActorComponent::StaticClassInstance.SetMetadataGetter(
        &UActorComponent::GetReflectedMetadata);
    return true;
}();

