// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/BillboardComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UBillboardComponent ----
UClass UBillboardComponent::StaticClassInstance(
    "UBillboardComponent",
    &UPrimitiveComponent::StaticClassInstance,
    sizeof(UBillboardComponent),
    CF_None
);
FClassRegistrar UBillboardComponent::s_Registrar(&UBillboardComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UBillboardComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UBillboardComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "Material", offsetof(UBillboardComponent, MaterialSlot), GetBuiltinPropertyType(EPropertyType::MaterialSlot), EPF_None, 0.0f, 0.0f, 0.1f, &UBillboardComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "Material", offsetof(UBillboardComponent, MaterialSlot), GetBuiltinPropertyType(EPropertyType::MaterialSlot), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UBillboardComponent_EditorMeta_26{ "Default", "" };
            return FPropertyMetadata{ "Width", offsetof(UBillboardComponent, Width), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.1f, 100.0f, 0.1f, &UBillboardComponent_EditorMeta_26 };
        }(),
        #else
        FPropertyMetadata{ "Width", offsetof(UBillboardComponent, Width), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.1f, 100.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UBillboardComponent_EditorMeta_34{ "Default", "" };
            return FPropertyMetadata{ "Height", offsetof(UBillboardComponent, Height), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.1f, 100.0f, 0.1f, &UBillboardComponent_EditorMeta_34 };
        }(),
        #else
        FPropertyMetadata{ "Height", offsetof(UBillboardComponent, Height), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.1f, 100.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool UBillboardComponent_MetaRegistered = []() {
    UBillboardComponent::StaticClassInstance.SetMetadataGetter(
        &UBillboardComponent::GetReflectedMetadata);
    return true;
}();

