// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/CameraComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UCameraComponent ----
UClass UCameraComponent::StaticClassInstance(
    "UCameraComponent",
    &USceneComponent::StaticClassInstance,
    sizeof(UCameraComponent),
    CF_None
);
FClassRegistrar UCameraComponent::s_Registrar(&UCameraComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UCameraComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "Follow Subject Auto", offsetof(UCameraComponent, bUseOwnerAsTarget), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UCameraComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "Follow Subject Auto", offsetof(UCameraComponent, bUseOwnerAsTarget), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_26{ "Default", "" };
            return FPropertyMetadata{ "Follow Target", offsetof(UCameraComponent, TargetActorUUID), GetBuiltinPropertyType(EPropertyType::ActorRef), EPF_None, 0.0f, 0.0f, 0.1f, &UCameraComponent_EditorMeta_26 };
        }(),
        #else
        FPropertyMetadata{ "Follow Target", offsetof(UCameraComponent, TargetActorUUID), GetBuiltinPropertyType(EPropertyType::ActorRef), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_34{ "Default", "" };
            return FPropertyMetadata{ "Follow Offset", offsetof(UCameraComponent, TargetOffset), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f, &UCameraComponent_EditorMeta_34 };
        }(),
        #else
        FPropertyMetadata{ "Follow Offset", offsetof(UCameraComponent, TargetOffset), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_42{ "Default", "" };
            return FPropertyMetadata{ "Eye Height", offsetof(UCameraComponent, EyeHeight), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 1000.0f, 0.01f, &UCameraComponent_EditorMeta_42 };
        }(),
        #else
        FPropertyMetadata{ "Eye Height", offsetof(UCameraComponent, EyeHeight), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 1000.0f, 0.01f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_50{ "Default", "" };
            return FPropertyMetadata{ "First Person Use Control Rotation", offsetof(UCameraComponent, bFirstPersonUseControlRotation), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UCameraComponent_EditorMeta_50 };
        }(),
        #else
        FPropertyMetadata{ "First Person Use Control Rotation", offsetof(UCameraComponent, bFirstPersonUseControlRotation), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_58{ "Default", "" };
            return FPropertyMetadata{ "Back Distance", offsetof(UCameraComponent, BackDistance), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 10000.0f, 0.1f, &UCameraComponent_EditorMeta_58 };
        }(),
        #else
        FPropertyMetadata{ "Back Distance", offsetof(UCameraComponent, BackDistance), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 10000.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_66{ "Default", "" };
            return FPropertyMetadata{ "Height", offsetof(UCameraComponent, Height), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, -10000.0f, 10000.0f, 0.1f, &UCameraComponent_EditorMeta_66 };
        }(),
        #else
        FPropertyMetadata{ "Height", offsetof(UCameraComponent, Height), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, -10000.0f, 10000.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_74{ "Default", "" };
            return FPropertyMetadata{ "Side Offset", offsetof(UCameraComponent, SideOffset), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, -10000.0f, 10000.0f, 0.1f, &UCameraComponent_EditorMeta_74 };
        }(),
        #else
        FPropertyMetadata{ "Side Offset", offsetof(UCameraComponent, SideOffset), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, -10000.0f, 10000.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_82{ "Default", "" };
            return FPropertyMetadata{ "View Offset", offsetof(UCameraComponent, ViewOffset), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f, &UCameraComponent_EditorMeta_82 };
        }(),
        #else
        FPropertyMetadata{ "View Offset", offsetof(UCameraComponent, ViewOffset), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_90{ "Default", "" };
            return FPropertyMetadata{ "Use Target Forward", offsetof(UCameraComponent, bUseTargetForward), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UCameraComponent_EditorMeta_90 };
        }(),
        #else
        FPropertyMetadata{ "Use Target Forward", offsetof(UCameraComponent, bUseTargetForward), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_98{ "Default", "" };
            return FPropertyMetadata{ "Use Control Rotation Yaw", offsetof(UCameraComponent, bUseControlRotationYaw), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UCameraComponent_EditorMeta_98 };
        }(),
        #else
        FPropertyMetadata{ "Use Control Rotation Yaw", offsetof(UCameraComponent, bUseControlRotationYaw), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_106{ "Default", "" };
            return FPropertyMetadata{ "Enable Look Ahead", offsetof(UCameraComponent, bEnableLookAhead), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UCameraComponent_EditorMeta_106 };
        }(),
        #else
        FPropertyMetadata{ "Enable Look Ahead", offsetof(UCameraComponent, bEnableLookAhead), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_114{ "Default", "" };
            return FPropertyMetadata{ "Look Ahead Distance", offsetof(UCameraComponent, LookAheadDistance), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 10000.0f, 0.1f, &UCameraComponent_EditorMeta_114 };
        }(),
        #else
        FPropertyMetadata{ "Look Ahead Distance", offsetof(UCameraComponent, LookAheadDistance), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 10000.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_122{ "Default", "" };
            return FPropertyMetadata{ "Look Ahead Lag Speed", offsetof(UCameraComponent, LookAheadLagSpeed), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100.0f, 0.1f, &UCameraComponent_EditorMeta_122 };
        }(),
        #else
        FPropertyMetadata{ "Look Ahead Lag Speed", offsetof(UCameraComponent, LookAheadLagSpeed), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_130{ "Default", "" };
            return FPropertyMetadata{ "Stabilize Vertical In Orthographic", offsetof(UCameraComponent, bStabilizeVerticalInOrthographic), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UCameraComponent_EditorMeta_130 };
        }(),
        #else
        FPropertyMetadata{ "Stabilize Vertical In Orthographic", offsetof(UCameraComponent, bStabilizeVerticalInOrthographic), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_138{ "Default", "" };
            return FPropertyMetadata{ "Vertical Dead Zone", offsetof(UCameraComponent, VerticalDeadZone), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 10000.0f, 0.01f, &UCameraComponent_EditorMeta_138 };
        }(),
        #else
        FPropertyMetadata{ "Vertical Dead Zone", offsetof(UCameraComponent, VerticalDeadZone), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 10000.0f, 0.01f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_146{ "Default", "" };
            return FPropertyMetadata{ "Vertical Follow Strength", offsetof(UCameraComponent, VerticalFollowStrength), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 1.0f, 0.01f, &UCameraComponent_EditorMeta_146 };
        }(),
        #else
        FPropertyMetadata{ "Vertical Follow Strength", offsetof(UCameraComponent, VerticalFollowStrength), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 1.0f, 0.01f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCameraComponent_EditorMeta_154{ "Default", "" };
            return FPropertyMetadata{ "Vertical Lag Speed", offsetof(UCameraComponent, VerticalLagSpeed), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100.0f, 0.1f, &UCameraComponent_EditorMeta_154 };
        }(),
        #else
        FPropertyMetadata{ "Vertical Lag Speed", offsetof(UCameraComponent, VerticalLagSpeed), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool UCameraComponent_MetaRegistered = []() {
    UCameraComponent::StaticClassInstance.SetMetadataGetter(
        &UCameraComponent::GetReflectedMetadata);
    return true;
}();

