// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/ControllerInputComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UControllerInputComponent ----
UClass UControllerInputComponent::StaticClassInstance(
    "UControllerInputComponent",
    &UActorComponent::StaticClassInstance,
    sizeof(UControllerInputComponent),
    CF_None
);
FClassRegistrar UControllerInputComponent::s_Registrar(&UControllerInputComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UControllerInputComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UControllerInputComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "Move Speed", offsetof(UControllerInputComponent, MoveSpeed), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100000.0f, 0.1f, &UControllerInputComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "Move Speed", offsetof(UControllerInputComponent, MoveSpeed), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100000.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UControllerInputComponent_EditorMeta_26{ "Default", "" };
            return FPropertyMetadata{ "Sprint Multiplier", offsetof(UControllerInputComponent, SprintMultiplier), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100.0f, 0.1f, &UControllerInputComponent_EditorMeta_26 };
        }(),
        #else
        FPropertyMetadata{ "Sprint Multiplier", offsetof(UControllerInputComponent, SprintMultiplier), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UControllerInputComponent_EditorMeta_34{ "Default", "" };
            return FPropertyMetadata{ "Look Sensitivity", offsetof(UControllerInputComponent, LookSensitivity), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100.0f, 0.01f, &UControllerInputComponent_EditorMeta_34 };
        }(),
        #else
        FPropertyMetadata{ "Look Sensitivity", offsetof(UControllerInputComponent, LookSensitivity), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100.0f, 0.01f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UControllerInputComponent_EditorMeta_42{ "Default", "" };
            return FPropertyMetadata{ "Min Pitch", offsetof(UControllerInputComponent, MinPitch), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, -180.0f, 180.0f, 0.1f, &UControllerInputComponent_EditorMeta_42 };
        }(),
        #else
        FPropertyMetadata{ "Min Pitch", offsetof(UControllerInputComponent, MinPitch), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, -180.0f, 180.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UControllerInputComponent_EditorMeta_50{ "Default", "" };
            return FPropertyMetadata{ "Max Pitch", offsetof(UControllerInputComponent, MaxPitch), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, -180.0f, 180.0f, 0.1f, &UControllerInputComponent_EditorMeta_50 };
        }(),
        #else
        FPropertyMetadata{ "Max Pitch", offsetof(UControllerInputComponent, MaxPitch), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, -180.0f, 180.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool UControllerInputComponent_MetaRegistered = []() {
    UControllerInputComponent::StaticClassInstance.SetMetadataGetter(
        &UControllerInputComponent::GetReflectedMetadata);
    return true;
}();

