// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/CylindricalBillboardComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UCylindricalBillboardComponent ----
UClass UCylindricalBillboardComponent::StaticClassInstance(
    "UCylindricalBillboardComponent",
    &UBillboardComponent::StaticClassInstance,
    sizeof(UCylindricalBillboardComponent),
    CF_None
);
FClassRegistrar UCylindricalBillboardComponent::s_Registrar(&UCylindricalBillboardComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UCylindricalBillboardComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UCylindricalBillboardComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "BillboardAxis", offsetof(UCylindricalBillboardComponent, BillboardAxis), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f, &UCylindricalBillboardComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "BillboardAxis", offsetof(UCylindricalBillboardComponent, BillboardAxis), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool UCylindricalBillboardComponent_MetaRegistered = []() {
    UCylindricalBillboardComponent::StaticClassInstance.SetMetadataGetter(
        &UCylindricalBillboardComponent::GetReflectedMetadata);
    return true;
}();

