// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#pragma once
#include "Object/ReflectionMacros.h"
#include <vector>

#undef  CURRENT_FILE_ID
#define CURRENT_FILE_ID DecalComponent_h_LINE_

// ---- UDecalComponent ----
#define DecalComponent_h_LINE_15 \
    using Super = UPrimitiveComponent; \
    static UClass StaticClassInstance; \
    static FClassRegistrar s_Registrar; \
    static UClass* StaticClass() { return &StaticClassInstance; } \
    virtual UClass* GetClass() const override { return StaticClass(); } \
    static const std::vector<FPropertyMetadata>& GetReflectedMetadata();

