// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/DecalComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UDecalComponent ----
UClass UDecalComponent::StaticClassInstance(
    "UDecalComponent",
    &UPrimitiveComponent::StaticClassInstance,
    sizeof(UDecalComponent),
    CF_None
);
FClassRegistrar UDecalComponent::s_Registrar(&UDecalComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UDecalComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UDecalComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "Material", offsetof(UDecalComponent, MaterialSlot), GetBuiltinPropertyType(EPropertyType::MaterialSlot), EPF_None, 0.0f, 0.0f, 0.1f, &UDecalComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "Material", offsetof(UDecalComponent, MaterialSlot), GetBuiltinPropertyType(EPropertyType::MaterialSlot), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UDecalComponent_EditorMeta_26{ "Default", "" };
            return FPropertyMetadata{ "Color", offsetof(UDecalComponent, Color), GetBuiltinPropertyType(EPropertyType::Vec4), EPF_None, 0.0f, 0.0f, 0.1f, &UDecalComponent_EditorMeta_26 };
        }(),
        #else
        FPropertyMetadata{ "Color", offsetof(UDecalComponent, Color), GetBuiltinPropertyType(EPropertyType::Vec4), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UDecalComponent_EditorMeta_34{ "Default", "" };
            return FPropertyMetadata{ "FadeInDelay", offsetof(UDecalComponent, FadeInDelay), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 0.0f, 0.1f, &UDecalComponent_EditorMeta_34 };
        }(),
        #else
        FPropertyMetadata{ "FadeInDelay", offsetof(UDecalComponent, FadeInDelay), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UDecalComponent_EditorMeta_42{ "Default", "" };
            return FPropertyMetadata{ "FadeInDuration", offsetof(UDecalComponent, FadeInDuration), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 0.0f, 0.1f, &UDecalComponent_EditorMeta_42 };
        }(),
        #else
        FPropertyMetadata{ "FadeInDuration", offsetof(UDecalComponent, FadeInDuration), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UDecalComponent_EditorMeta_50{ "Default", "" };
            return FPropertyMetadata{ "FadeOutDelay", offsetof(UDecalComponent, FadeOutDelay), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 0.0f, 0.1f, &UDecalComponent_EditorMeta_50 };
        }(),
        #else
        FPropertyMetadata{ "FadeOutDelay", offsetof(UDecalComponent, FadeOutDelay), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UDecalComponent_EditorMeta_58{ "Default", "" };
            return FPropertyMetadata{ "FadeOutDuration", offsetof(UDecalComponent, FadeOutDuration), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 0.0f, 0.1f, &UDecalComponent_EditorMeta_58 };
        }(),
        #else
        FPropertyMetadata{ "FadeOutDuration", offsetof(UDecalComponent, FadeOutDuration), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool UDecalComponent_MetaRegistered = []() {
    UDecalComponent::StaticClassInstance.SetMetadataGetter(
        &UDecalComponent::GetReflectedMetadata);
    return true;
}();

