// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/GizmoComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UGizmoComponent ----
UClass UGizmoComponent::StaticClassInstance(
    "UGizmoComponent",
    &UPrimitiveComponent::StaticClassInstance,
    sizeof(UGizmoComponent),
    CF_None
);
FClassRegistrar UGizmoComponent::s_Registrar(&UGizmoComponent::StaticClassInstance);

