// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#pragma once
#include "Object/ReflectionMacros.h"
#include <vector>

#undef  CURRENT_FILE_ID
#define CURRENT_FILE_ID HeightFogComponent_h_LINE_

// ---- UHeightFogComponent ----
#define HeightFogComponent_h_LINE_11 \
    using Super = USceneComponent; \
    static UClass StaticClassInstance; \
    static FClassRegistrar s_Registrar; \
    static UClass* StaticClass() { return &StaticClassInstance; } \
    virtual UClass* GetClass() const override { return StaticClass(); } \
    static const std::vector<FPropertyMetadata>& GetReflectedMetadata();

