// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/HeightFogComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UHeightFogComponent ----
UClass UHeightFogComponent::StaticClassInstance(
    "UHeightFogComponent",
    &USceneComponent::StaticClassInstance,
    sizeof(UHeightFogComponent),
    CF_None
);
FClassRegistrar UHeightFogComponent::s_Registrar(&UHeightFogComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UHeightFogComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UHeightFogComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "Fog Density", offsetof(UHeightFogComponent, FogDensity), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 0.05f, 0.001f, &UHeightFogComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "Fog Density", offsetof(UHeightFogComponent, FogDensity), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 0.05f, 0.001f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UHeightFogComponent_EditorMeta_26{ "Default", "" };
            return FPropertyMetadata{ "Height Falloff", offsetof(UHeightFogComponent, FogHeightFalloff), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.001f, 5.0f, 0.01f, &UHeightFogComponent_EditorMeta_26 };
        }(),
        #else
        FPropertyMetadata{ "Height Falloff", offsetof(UHeightFogComponent, FogHeightFalloff), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.001f, 5.0f, 0.01f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UHeightFogComponent_EditorMeta_34{ "Default", "" };
            return FPropertyMetadata{ "Start Distance", offsetof(UHeightFogComponent, StartDistance), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100000.0f, 1.0f, &UHeightFogComponent_EditorMeta_34 };
        }(),
        #else
        FPropertyMetadata{ "Start Distance", offsetof(UHeightFogComponent, StartDistance), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100000.0f, 1.0f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UHeightFogComponent_EditorMeta_42{ "Default", "" };
            return FPropertyMetadata{ "Cutoff Distance", offsetof(UHeightFogComponent, FogCutoffDistance), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100000.0f, 1.0f, &UHeightFogComponent_EditorMeta_42 };
        }(),
        #else
        FPropertyMetadata{ "Cutoff Distance", offsetof(UHeightFogComponent, FogCutoffDistance), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100000.0f, 1.0f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UHeightFogComponent_EditorMeta_50{ "Default", "" };
            return FPropertyMetadata{ "Max Opacity", offsetof(UHeightFogComponent, FogMaxOpacity), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 1.0f, 0.01f, &UHeightFogComponent_EditorMeta_50 };
        }(),
        #else
        FPropertyMetadata{ "Max Opacity", offsetof(UHeightFogComponent, FogMaxOpacity), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 1.0f, 0.01f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UHeightFogComponent_EditorMeta_58{ "Default", "" };
            return FPropertyMetadata{ "Inscattering Color", offsetof(UHeightFogComponent, FogInscatteringColor), GetBuiltinPropertyType(EPropertyType::Color4), EPF_None, 0.0f, 0.0f, 0.1f, &UHeightFogComponent_EditorMeta_58 };
        }(),
        #else
        FPropertyMetadata{ "Inscattering Color", offsetof(UHeightFogComponent, FogInscatteringColor), GetBuiltinPropertyType(EPropertyType::Color4), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool UHeightFogComponent_MetaRegistered = []() {
    UHeightFogComponent::StaticClassInstance.SetMetadataGetter(
        &UHeightFogComponent::GetReflectedMetadata);
    return true;
}();

