// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/MeshComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UMeshComponent ----
UClass UMeshComponent::StaticClassInstance(
    "UMeshComponent",
    &UPrimitiveComponent::StaticClassInstance,
    sizeof(UMeshComponent),
    CF_None
);
FClassRegistrar UMeshComponent::s_Registrar(&UMeshComponent::StaticClassInstance);

