// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/PawnOrientationComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UPawnOrientationComponent ----
UClass UPawnOrientationComponent::StaticClassInstance(
    "UPawnOrientationComponent",
    &UActorComponent::StaticClassInstance,
    sizeof(UPawnOrientationComponent),
    CF_None
);
FClassRegistrar UPawnOrientationComponent::s_Registrar(&UPawnOrientationComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UPawnOrientationComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UPawnOrientationComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "Rotation Speed", offsetof(UPawnOrientationComponent, RotationSpeed), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 10000.0f, 1.0f, &UPawnOrientationComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "Rotation Speed", offsetof(UPawnOrientationComponent, RotationSpeed), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 10000.0f, 1.0f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UPawnOrientationComponent_EditorMeta_26{ "Default", "" };
            return FPropertyMetadata{ "Yaw Only", offsetof(UPawnOrientationComponent, bYawOnly), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UPawnOrientationComponent_EditorMeta_26 };
        }(),
        #else
        FPropertyMetadata{ "Yaw Only", offsetof(UPawnOrientationComponent, bYawOnly), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UPawnOrientationComponent_EditorMeta_34{ "Default", "" };
            return FPropertyMetadata{ "Min Facing Input Size", offsetof(UPawnOrientationComponent, MinFacingInputSize), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 10000.0f, 0.01f, &UPawnOrientationComponent_EditorMeta_34 };
        }(),
        #else
        FPropertyMetadata{ "Min Facing Input Size", offsetof(UPawnOrientationComponent, MinFacingInputSize), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 10000.0f, 0.01f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UPawnOrientationComponent_EditorMeta_42{ "Default", "" };
            return FPropertyMetadata{ "Min Facing Speed", offsetof(UPawnOrientationComponent, MinFacingSpeed), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 10000.0f, 0.1f, &UPawnOrientationComponent_EditorMeta_42 };
        }(),
        #else
        FPropertyMetadata{ "Min Facing Speed", offsetof(UPawnOrientationComponent, MinFacingSpeed), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 10000.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UPawnOrientationComponent_EditorMeta_50{ "Default", "" };
            return FPropertyMetadata{ "Custom Facing Direction", offsetof(UPawnOrientationComponent, CustomFacingDirection), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f, &UPawnOrientationComponent_EditorMeta_50 };
        }(),
        #else
        FPropertyMetadata{ "Custom Facing Direction", offsetof(UPawnOrientationComponent, CustomFacingDirection), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool UPawnOrientationComponent_MetaRegistered = []() {
    UPawnOrientationComponent::StaticClassInstance.SetMetadataGetter(
        &UPawnOrientationComponent::GetReflectedMetadata);
    return true;
}();

