// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/PrimitiveComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UPrimitiveComponent ----
UClass UPrimitiveComponent::StaticClassInstance(
    "UPrimitiveComponent",
    &USceneComponent::StaticClassInstance,
    sizeof(UPrimitiveComponent),
    CF_None
);
FClassRegistrar UPrimitiveComponent::s_Registrar(&UPrimitiveComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UPrimitiveComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UPrimitiveComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "Visible", offsetof(UPrimitiveComponent, bIsVisible), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UPrimitiveComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "Visible", offsetof(UPrimitiveComponent, bIsVisible), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UPrimitiveComponent_EditorMeta_26{ "Default", "" };
            return FPropertyMetadata{ "Cast Shadow", offsetof(UPrimitiveComponent, bCastShadow), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UPrimitiveComponent_EditorMeta_26 };
        }(),
        #else
        FPropertyMetadata{ "Cast Shadow", offsetof(UPrimitiveComponent, bCastShadow), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UPrimitiveComponent_EditorMeta_34{ "Default", "" };
            return FPropertyMetadata{ "Two Sided Shadow", offsetof(UPrimitiveComponent, bCastShadowAsTwoSided), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UPrimitiveComponent_EditorMeta_34 };
        }(),
        #else
        FPropertyMetadata{ "Two Sided Shadow", offsetof(UPrimitiveComponent, bCastShadowAsTwoSided), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UPrimitiveComponent_EditorMeta_42{ "Default", "" };
            return FPropertyMetadata{ "Blocks Movement", offsetof(UPrimitiveComponent, bBlocksMovement), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UPrimitiveComponent_EditorMeta_42 };
        }(),
        #else
        FPropertyMetadata{ "Blocks Movement", offsetof(UPrimitiveComponent, bBlocksMovement), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UPrimitiveComponent_EditorMeta_50{ "Default", "" };
            return FPropertyMetadata{ "Generate Overlap Events", offsetof(UPrimitiveComponent, bGenerateOverlapEvents), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UPrimitiveComponent_EditorMeta_50 };
        }(),
        #else
        FPropertyMetadata{ "Generate Overlap Events", offsetof(UPrimitiveComponent, bGenerateOverlapEvents), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool UPrimitiveComponent_MetaRegistered = []() {
    UPrimitiveComponent::StaticClassInstance.SetMetadataGetter(
        &UPrimitiveComponent::GetReflectedMetadata);
    return true;
}();

