// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/SceneComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- USceneComponent ----
UClass USceneComponent::StaticClassInstance(
    "USceneComponent",
    &UActorComponent::StaticClassInstance,
    sizeof(USceneComponent),
    CF_None
);
FClassRegistrar USceneComponent::s_Registrar(&USceneComponent::StaticClassInstance);

