// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/SkeletalGizmoComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- USkeletalGizmoComponent ----
UClass USkeletalGizmoComponent::StaticClassInstance(
    "USkeletalGizmoComponent",
    &UObject::StaticClassInstance,
    sizeof(USkeletalGizmoComponent),
    CF_None
);
FClassRegistrar USkeletalGizmoComponent::s_Registrar(&USkeletalGizmoComponent::StaticClassInstance);

