// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#pragma once
#include "Object/ReflectionMacros.h"
#include <vector>

#undef  CURRENT_FILE_ID
#define CURRENT_FILE_ID SkeletalGizmoComponent_h_LINE_

// ---- USkeletalGizmoComponent ----
#define SkeletalGizmoComponent_h_LINE_12 \
    static UClass StaticClassInstance; \
    static FClassRegistrar s_Registrar; \
    static UClass* StaticClass() { return &StaticClassInstance; } \
    virtual UClass* GetClass() const override { return StaticClass(); }

