// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/SkeletalMeshComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- USkeletalMeshComponent ----
UClass USkeletalMeshComponent::StaticClassInstance(
    "USkeletalMeshComponent",
    &USkinnedMeshComponent::StaticClassInstance,
    sizeof(USkeletalMeshComponent),
    CF_None
);
FClassRegistrar USkeletalMeshComponent::s_Registrar(&USkeletalMeshComponent::StaticClassInstance);

