// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/SkinnedMeshComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- USkinnedMeshComponent ----
UClass USkinnedMeshComponent::StaticClassInstance(
    "USkinnedMeshComponent",
    &UMeshComponent::StaticClassInstance,
    sizeof(USkinnedMeshComponent),
    CF_None
);
FClassRegistrar USkinnedMeshComponent::s_Registrar(&USkinnedMeshComponent::StaticClassInstance);

