// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/SpringArmComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- USpringArmComponent ----
UClass USpringArmComponent::StaticClassInstance(
    "USpringArmComponent",
    &USceneComponent::StaticClassInstance,
    sizeof(USpringArmComponent),
    CF_None
);
FClassRegistrar USpringArmComponent::s_Registrar(&USpringArmComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& USpringArmComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata USpringArmComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "Target Arm Length", offsetof(USpringArmComponent, TargetArmLength), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 10000.0f, 0.1f, &USpringArmComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "Target Arm Length", offsetof(USpringArmComponent, TargetArmLength), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 10000.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata USpringArmComponent_EditorMeta_26{ "Default", "" };
            return FPropertyMetadata{ "Target Offset", offsetof(USpringArmComponent, TargetOffset), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f, &USpringArmComponent_EditorMeta_26 };
        }(),
        #else
        FPropertyMetadata{ "Target Offset", offsetof(USpringArmComponent, TargetOffset), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata USpringArmComponent_EditorMeta_34{ "Default", "" };
            return FPropertyMetadata{ "Socket Offset", offsetof(USpringArmComponent, SocketOffset), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f, &USpringArmComponent_EditorMeta_34 };
        }(),
        #else
        FPropertyMetadata{ "Socket Offset", offsetof(USpringArmComponent, SocketOffset), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata USpringArmComponent_EditorMeta_42{ "Default", "" };
            return FPropertyMetadata{ "Do Collision Test", offsetof(USpringArmComponent, bDoCollisionTest), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &USpringArmComponent_EditorMeta_42 };
        }(),
        #else
        FPropertyMetadata{ "Do Collision Test", offsetof(USpringArmComponent, bDoCollisionTest), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata USpringArmComponent_EditorMeta_50{ "Default", "" };
            return FPropertyMetadata{ "Probe Size", offsetof(USpringArmComponent, ProbeSize), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 1000.0f, 0.01f, &USpringArmComponent_EditorMeta_50 };
        }(),
        #else
        FPropertyMetadata{ "Probe Size", offsetof(USpringArmComponent, ProbeSize), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 1000.0f, 0.01f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata USpringArmComponent_EditorMeta_58{ "Default", "" };
            return FPropertyMetadata{ "Use Pawn Control Rotation", offsetof(USpringArmComponent, bUsePawnControlRotation), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &USpringArmComponent_EditorMeta_58 };
        }(),
        #else
        FPropertyMetadata{ "Use Pawn Control Rotation", offsetof(USpringArmComponent, bUsePawnControlRotation), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata USpringArmComponent_EditorMeta_66{ "Default", "" };
            return FPropertyMetadata{ "Inherit Pitch", offsetof(USpringArmComponent, bInheritPitch), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &USpringArmComponent_EditorMeta_66 };
        }(),
        #else
        FPropertyMetadata{ "Inherit Pitch", offsetof(USpringArmComponent, bInheritPitch), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata USpringArmComponent_EditorMeta_74{ "Default", "" };
            return FPropertyMetadata{ "Inherit Yaw", offsetof(USpringArmComponent, bInheritYaw), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &USpringArmComponent_EditorMeta_74 };
        }(),
        #else
        FPropertyMetadata{ "Inherit Yaw", offsetof(USpringArmComponent, bInheritYaw), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata USpringArmComponent_EditorMeta_82{ "Default", "" };
            return FPropertyMetadata{ "Inherit Roll", offsetof(USpringArmComponent, bInheritRoll), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &USpringArmComponent_EditorMeta_82 };
        }(),
        #else
        FPropertyMetadata{ "Inherit Roll", offsetof(USpringArmComponent, bInheritRoll), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata USpringArmComponent_EditorMeta_90{ "Default", "" };
            return FPropertyMetadata{ "Enable Camera Lag", offsetof(USpringArmComponent, bEnableCameraLag), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &USpringArmComponent_EditorMeta_90 };
        }(),
        #else
        FPropertyMetadata{ "Enable Camera Lag", offsetof(USpringArmComponent, bEnableCameraLag), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata USpringArmComponent_EditorMeta_98{ "Default", "" };
            return FPropertyMetadata{ "Camera Lag Speed", offsetof(USpringArmComponent, CameraLagSpeed), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100.0f, 0.1f, &USpringArmComponent_EditorMeta_98 };
        }(),
        #else
        FPropertyMetadata{ "Camera Lag Speed", offsetof(USpringArmComponent, CameraLagSpeed), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool USpringArmComponent_MetaRegistered = []() {
    USpringArmComponent::StaticClassInstance.SetMetadataGetter(
        &USpringArmComponent::GetReflectedMetadata);
    return true;
}();

