// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/StaticMeshComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UStaticMeshComponent ----
UClass UStaticMeshComponent::StaticClassInstance(
    "UStaticMeshComponent",
    &UMeshComponent::StaticClassInstance,
    sizeof(UStaticMeshComponent),
    CF_None
);
FClassRegistrar UStaticMeshComponent::s_Registrar(&UStaticMeshComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UStaticMeshComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static const FPropertyTypeDesc UStaticMeshComponent_PropType_0{ EPropertyType::ObjectRef, nullptr, nullptr, 0, FindRegisteredClassByName("UStaticMesh"), nullptr, nullptr, nullptr, nullptr, nullptr, nullptr };
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UStaticMeshComponent_EditorMeta_19{ "Default", "" };
            return FPropertyMetadata{ "Static Mesh", offsetof(UStaticMeshComponent, StaticMeshPath), &UStaticMeshComponent_PropType_0, EPF_None, 0.0f, 0.0f, 0.1f, &UStaticMeshComponent_EditorMeta_19 };
        }(),
        #else
        FPropertyMetadata{ "Static Mesh", offsetof(UStaticMeshComponent, StaticMeshPath), &UStaticMeshComponent_PropType_0, EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool UStaticMeshComponent_MetaRegistered = []() {
    UStaticMeshComponent::StaticClassInstance.SetMetadataGetter(
        &UStaticMeshComponent::GetReflectedMetadata);
    return true;
}();

