// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/SubUVComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- USubUVComponent ----
UClass USubUVComponent::StaticClassInstance(
    "USubUVComponent",
    &UBillboardComponent::StaticClassInstance,
    sizeof(USubUVComponent),
    CF_None
);
FClassRegistrar USubUVComponent::s_Registrar(&USubUVComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& USubUVComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata USubUVComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "Particle", offsetof(USubUVComponent, ParticleName), GetBuiltinPropertyType(EPropertyType::Name), EPF_None, 0.0f, 0.0f, 0.1f, &USubUVComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "Particle", offsetof(USubUVComponent, ParticleName), GetBuiltinPropertyType(EPropertyType::Name), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata USubUVComponent_EditorMeta_26{ "Default", "" };
            return FPropertyMetadata{ "bLoop", offsetof(USubUVComponent, bLoop), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &USubUVComponent_EditorMeta_26 };
        }(),
        #else
        FPropertyMetadata{ "bLoop", offsetof(USubUVComponent, bLoop), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool USubUVComponent_MetaRegistered = []() {
    USubUVComponent::StaticClassInstance.SetMetadataGetter(
        &USubUVComponent::GetReflectedMetadata);
    return true;
}();

