// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/TextRenderComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UTextRenderComponent ----
UClass UTextRenderComponent::StaticClassInstance(
    "UTextRenderComponent",
    &UBillboardComponent::StaticClassInstance,
    sizeof(UTextRenderComponent),
    CF_None
);
FClassRegistrar UTextRenderComponent::s_Registrar(&UTextRenderComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UTextRenderComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UTextRenderComponent_EditorMeta_18{ "Default", "" };
            return FPropertyMetadata{ "Text", offsetof(UTextRenderComponent, Text), GetBuiltinPropertyType(EPropertyType::String), EPF_None, 0.0f, 0.0f, 0.1f, &UTextRenderComponent_EditorMeta_18 };
        }(),
        #else
        FPropertyMetadata{ "Text", offsetof(UTextRenderComponent, Text), GetBuiltinPropertyType(EPropertyType::String), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UTextRenderComponent_EditorMeta_26{ "Default", "" };
            return FPropertyMetadata{ "Font", offsetof(UTextRenderComponent, FontName), GetBuiltinPropertyType(EPropertyType::Name), EPF_None, 0.0f, 0.0f, 0.1f, &UTextRenderComponent_EditorMeta_26 };
        }(),
        #else
        FPropertyMetadata{ "Font", offsetof(UTextRenderComponent, FontName), GetBuiltinPropertyType(EPropertyType::Name), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UTextRenderComponent_EditorMeta_34{ "Default", "" };
            return FPropertyMetadata{ "Font Size", offsetof(UTextRenderComponent, FontSize), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.1f, 100.0f, 0.1f, &UTextRenderComponent_EditorMeta_34 };
        }(),
        #else
        FPropertyMetadata{ "Font Size", offsetof(UTextRenderComponent, FontSize), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.1f, 100.0f, 0.1f },
        #endif
    };
    return Props;
}

static bool UTextRenderComponent_MetaRegistered = []() {
    UTextRenderComponent::StaticClassInstance.SetMetadataGetter(
        &UTextRenderComponent::GetReflectedMetadata);
    return true;
}();

