// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/GameFramework/Light/AmbientLightActor.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- AAmbientLightActor ----
UClass AAmbientLightActor::StaticClassInstance(
    "AAmbientLightActor",
    &AActor::StaticClassInstance,
    sizeof(AAmbientLightActor),
    CF_None
);
FClassRegistrar AAmbientLightActor::s_Registrar(&AAmbientLightActor::StaticClassInstance);

