// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/GameFramework/Light/DirectionalLightActor.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- ADirectionalLightActor ----
UClass ADirectionalLightActor::StaticClassInstance(
    "ADirectionalLightActor",
    &AActor::StaticClassInstance,
    sizeof(ADirectionalLightActor),
    CF_None
);
FClassRegistrar ADirectionalLightActor::s_Registrar(&ADirectionalLightActor::StaticClassInstance);

