// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/GameFramework/Light/PointLightActor.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- APointLightActor ----
UClass APointLightActor::StaticClassInstance(
    "APointLightActor",
    &AActor::StaticClassInstance,
    sizeof(APointLightActor),
    CF_None
);
FClassRegistrar APointLightActor::s_Registrar(&APointLightActor::StaticClassInstance);

