// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/GameFramework/Light/SpotLightActor.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- ASpotLightActor ----
UClass ASpotLightActor::StaticClassInstance(
    "ASpotLightActor",
    &AActor::StaticClassInstance,
    sizeof(ASpotLightActor),
    CF_None
);
FClassRegistrar ASpotLightActor::s_Registrar(&ASpotLightActor::StaticClassInstance);

