// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Games/Crossy/Components/HopMovementComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UHopMovementComponent ----
UClass UHopMovementComponent::StaticClassInstance(
    "UHopMovementComponent",
    &UMovementComponent::StaticClassInstance,
    sizeof(UHopMovementComponent),
    CF_None
);
FClassRegistrar UHopMovementComponent::s_Registrar(&UHopMovementComponent::StaticClassInstance);

const std::vector<FPropertyMetadata>& UHopMovementComponent::GetReflectedMetadata() {
    // Static type nodes mirror the reflected type graph and keep metadata address-stable.
    static const FPropertyTypeDesc UHopMovementComponent_PropType_5{ EPropertyType::ObjectRef, nullptr, nullptr, 0, FindRegisteredClassByName("USceneComponent"), nullptr, nullptr, nullptr, nullptr, nullptr, nullptr };
    static std::vector<FPropertyMetadata> Props = {
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UHopMovementComponent_EditorMeta_19{ "Default", "" };
            return FPropertyMetadata{ "Velocity", offsetof(UHopMovementComponent, Velocity), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 1.0f, &UHopMovementComponent_EditorMeta_19 };
        }(),
        #else
        FPropertyMetadata{ "Velocity", offsetof(UHopMovementComponent, Velocity), GetBuiltinPropertyType(EPropertyType::Vec3), EPF_None, 0.0f, 0.0f, 1.0f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UHopMovementComponent_EditorMeta_27{ "Default", "" };
            return FPropertyMetadata{ "Hop Coefficient", offsetof(UHopMovementComponent, HopCoefficient), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100.0f, 0.1f, &UHopMovementComponent_EditorMeta_27 };
        }(),
        #else
        FPropertyMetadata{ "Hop Coefficient", offsetof(UHopMovementComponent, HopCoefficient), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 100.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UHopMovementComponent_EditorMeta_35{ "Default", "" };
            return FPropertyMetadata{ "Hop Only When Moving", offsetof(UHopMovementComponent, bHopOnlyWhenMoving), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UHopMovementComponent_EditorMeta_35 };
        }(),
        #else
        FPropertyMetadata{ "Hop Only When Moving", offsetof(UHopMovementComponent, bHopOnlyWhenMoving), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UHopMovementComponent_EditorMeta_43{ "Default", "" };
            return FPropertyMetadata{ "Reset Hop When Idle", offsetof(UHopMovementComponent, bResetHopWhenIdle), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UHopMovementComponent_EditorMeta_43 };
        }(),
        #else
        FPropertyMetadata{ "Reset Hop When Idle", offsetof(UHopMovementComponent, bResetHopWhenIdle), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UHopMovementComponent_EditorMeta_51{ "Default", "" };
            return FPropertyMetadata{ "Simulating", offsetof(UHopMovementComponent, bSimulating), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f, &UHopMovementComponent_EditorMeta_51 };
        }(),
        #else
        FPropertyMetadata{ "Simulating", offsetof(UHopMovementComponent, bSimulating), GetBuiltinPropertyType(EPropertyType::Bool), EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UHopMovementComponent_EditorMeta_59{ "Default", "" };
            return FPropertyMetadata{ "Visual Hop Component", offsetof(UHopMovementComponent, VisualHopComponentPath), &UHopMovementComponent_PropType_5, EPF_None, 0.0f, 0.0f, 0.1f, &UHopMovementComponent_EditorMeta_59 };
        }(),
        #else
        FPropertyMetadata{ "Visual Hop Component", offsetof(UHopMovementComponent, VisualHopComponentPath), &UHopMovementComponent_PropType_5, EPF_None, 0.0f, 0.0f, 0.1f },
        #endif
        #if WITH_EDITOR
        []() -> FPropertyMetadata {
            static const FEditorPropertyMetadata UHopMovementComponent_EditorMeta_67{ "Default", "" };
            return FPropertyMetadata{ "Dash Duration", offsetof(UHopMovementComponent, DashDuration), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 5.0f, 0.01f, &UHopMovementComponent_EditorMeta_67 };
        }(),
        #else
        FPropertyMetadata{ "Dash Duration", offsetof(UHopMovementComponent, DashDuration), GetBuiltinPropertyType(EPropertyType::Float), EPF_None, 0.0f, 5.0f, 0.01f },
        #endif
    };
    return Props;
}

static bool UHopMovementComponent_MetaRegistered = []() {
    UHopMovementComponent::StaticClassInstance.SetMetadataGetter(
        &UHopMovementComponent::GetReflectedMetadata);
    return true;
}();

