// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Games/Crossy/Components/ParryComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UParryComponent ----
UClass UParryComponent::StaticClassInstance(
    "UParryComponent",
    &UActorComponent::StaticClassInstance,
    sizeof(UParryComponent),
    CF_None
);
FClassRegistrar UParryComponent::s_Registrar(&UParryComponent::StaticClassInstance);

