// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Games/Crossy/Components/ParryableProjectileComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UParryableProjectileComponent ----
UClass UParryableProjectileComponent::StaticClassInstance(
    "UParryableProjectileComponent",
    &UActorComponent::StaticClassInstance,
    sizeof(UParryableProjectileComponent),
    CF_None
);
FClassRegistrar UParryableProjectileComponent::s_Registrar(&UParryableProjectileComponent::StaticClassInstance);

