// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#pragma once
#include "Object/ReflectionMacros.h"
#include <vector>

#undef  CURRENT_FILE_ID
#define CURRENT_FILE_ID ParryComponent_h_LINE_

// ---- UParryComponent ----
#define ParryComponent_h_LINE_16 \
    using Super = UActorComponent; \
    static UClass StaticClassInstance; \
    static FClassRegistrar s_Registrar; \
    static UClass* StaticClass() { return &StaticClassInstance; } \
    virtual UClass* GetClass() const override { return StaticClass(); }

