// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "GameClient/GameClientEngine.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UGameClientEngine ----
UClass UGameClientEngine::StaticClassInstance(
    "UGameClientEngine",
    &UEngine::StaticClassInstance,
    sizeof(UGameClientEngine),
    CF_None
);
FClassRegistrar UGameClientEngine::s_Registrar(&UGameClientEngine::StaticClassInstance);

