// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Viewport/GameViewportClient.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UGameViewportClient ----
UClass UGameViewportClient::StaticClassInstance(
    "UGameViewportClient",
    &UObject::StaticClassInstance,
    sizeof(UGameViewportClient),
    CF_None
);
FClassRegistrar UGameViewportClient::s_Registrar(&UGameViewportClient::StaticClassInstance);

