// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Collision/BoxComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UBoxComponent ----
UClass UBoxComponent::StaticClassInstance(
    "UBoxComponent",
    &UShapeComponent::StaticClassInstance,
    sizeof(UBoxComponent),
    CF_None
);
FClassRegistrar UBoxComponent::s_Registrar(&UBoxComponent::StaticClassInstance);

