// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Collision/CapsuleComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UCapsuleComponent ----
UClass UCapsuleComponent::StaticClassInstance(
    "UCapsuleComponent",
    &UShapeComponent::StaticClassInstance,
    sizeof(UCapsuleComponent),
    CF_None
);
FClassRegistrar UCapsuleComponent::s_Registrar(&UCapsuleComponent::StaticClassInstance);

