// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Collision/ShapeComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- UShapeComponent ----
UClass UShapeComponent::StaticClassInstance(
    "UShapeComponent",
    &UPrimitiveComponent::StaticClassInstance,
    sizeof(UShapeComponent),
    CF_None
);
FClassRegistrar UShapeComponent::s_Registrar(&UShapeComponent::StaticClassInstance);

