// AUTO-GENERATED FILE - DO NOT EDIT.
// Generated by Scripts/GenerateReflectionHeaders.py

#include "Engine/Component/Collision/SphereComponent.h"
#include "Core/PropertyTypes.h"
#include <cstddef>
#include <vector>

// ---- USphereComponent ----
UClass USphereComponent::StaticClassInstance(
    "USphereComponent",
    &UShapeComponent::StaticClassInstance,
    sizeof(USphereComponent),
    CF_None
);
FClassRegistrar USphereComponent::s_Registrar(&USphereComponent::StaticClassInstance);

